version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/web
      - /web/node_modules
